#!/bin/bash
# Cart Recommendations Testing Script

echo "================================"
echo "AmazonGo Cart Recommendations"
echo "Testing Protocol"
echo "================================"
echo ""

echo "Step 1: Verify Services Running"
echo "--------------------------------"
echo "✓ Frontend (Vite) - Port 5174: http://localhost:5174"
echo "✓ Backend (Node.js) - Port 5000: http://localhost:5000/health"
echo "✓ ML Service (Python) - Port 8000: http://localhost:8000/health"
echo ""

echo "Step 2: Manual Testing Steps"
echo "----------------------------"
echo "1. Go to http://localhost:5174"
echo "2. If not logged in:"
echo "   - Click 'Register' or 'Login'"
echo "   - Create account or use test credentials"
echo "3. Navigate to /products page"
echo "4. Add at least 1 item to cart:"
echo "   - Click product card"
echo "   - Click 'Add to Cart' button"
echo "5. Go to cart page (/cart):"
echo "   - Should see cart items displayed"
echo "   - Should see 'Order Summary' section"
echo "   - Should see 'Recommended For You' section BELOW the cart"
echo "6. Verify recommendations:"
echo "   - If item is 'Book' → see books, bookmarks, stands"
echo "   - If item is 'Headphones' → see electronics, cables, chargers"
echo "   - etc."
echo ""

echo "Step 3: Debug if Blank Page Shows"
echo "----------------------------------"
echo "Open browser DevTools (F12) and check:"
echo ""
echo "A) Console Tab:"
echo "   - Look for red errors"
echo "   - Check if any 404 errors on /api/recommendations"
echo "   - Look for 'CartRecommendations' related messages"
echo ""
echo "B) Network Tab:"
echo "   - Add item to cart"
echo "   - Go to cart page"
echo "   - Look for POST request to /api/recommendations"
echo "   - Check response status (should be 200)"
echo "   - Check response body (should have 'recommendations' array)"
echo ""
echo "C) If seeing errors:"
echo "   - Clear localStorage: localStorage.clear()"
echo "   - Refresh page"
echo "   - Try again"
echo ""

echo "Step 4: Expected Flow"
echo "---------------------"
echo "HOME → PRODUCTS → ADD TO CART → CART PAGE"
echo "                                    ↓"
echo "                         Cart Items Displayed"
echo "                                    ↓"
echo "                         Order Summary Shows"
echo "                                    ↓"
echo "                    Recommendations Section"
echo "                    (Auto-loads related items)"
echo ""

echo "Step 5: File Changes Made"
echo "------------------------"
echo "✓ backend/controllers/recommendationController.js - Category-based logic"
echo "✓ backend/routes/recommendationRoutes.js - Removed auth requirement"
echo "✓ frontend/src/context/CartContext.jsx - Fixed circular imports"
echo "✓ frontend/src/context/RecommendationContext.jsx - Added proper state management"
echo "✓ frontend/src/components/CartRecommendations.jsx - New component"
echo "✓ frontend/src/pages/Cart.jsx - Integrated recommendations"
echo "✓ frontend/src/main.jsx - Added RecommendationProvider"
echo "✓ Multiple component imports - Fixed to use hooks/"
echo ""

echo "Step 6: Common Issues & Solutions"
echo "--------------------------------"
echo ""
echo "Issue: Blank/white page on /cart"
echo "Solution: Check console for errors, see Step 3 above"
echo ""
echo "Issue: Recommendations not showing"
echo "Solution: "
echo "  - Make sure cart has items"
echo "  - Check Network tab in DevTools"
echo "  - Look for /api/recommendations POST request"
echo ""
echo "Issue: Cart items not persisting"
echo "Solution:"
echo "  - Check if localStorage is working"
echo "  - Run: localStorage.clear() and retry"
echo ""
echo "Issue: 'useCart must be used within CartProvider' error"
echo "Solution:"
echo "  - Restart dev server (Ctrl+C and npm run dev)"
echo "  - Clear browser cache"
echo ""

echo "================================"
echo "Ready to test!"
echo "================================"
